insert into PartsSupplier (id, supplier_name) values (1, 'Emard and Sons');
insert into PartsSupplier (id, supplier_name) values (2, 'Fadel-Gottlieb');
insert into PartsSupplier (id, supplier_name) values (3, 'O''Reilly, Kris and Herzog');
insert into PartsSupplier (id, supplier_name) values (4, 'Prohaska, Johnson and Bruen');
insert into PartsSupplier (id, supplier_name) values (5, 'Cruickshank, Bergnaum and Doyle');
insert into PartsSupplier (id, supplier_name) values (6, 'Collins Inc');
insert into PartsSupplier (id, supplier_name) values (7, 'Schiller, Parisian and VonRueden');
insert into PartsSupplier (id, supplier_name) values (8, 'Murray-Corwin');
insert into PartsSupplier (id, supplier_name) values (9, 'Lynch, Heller and Prosacco');
insert into PartsSupplier (id, supplier_name) values (10, 'Lynch, Harber and Kerluke');
insert into PartsSupplier (id, supplier_name) values (11, 'Emard-Hamill');
insert into PartsSupplier (id, supplier_name) values (12, 'Pouros-Gutmann');
insert into PartsSupplier (id, supplier_name) values (13, 'Hilpert and Sons');
insert into PartsSupplier (id, supplier_name) values (14, 'Hudson-Gutkowski');
insert into PartsSupplier (id, supplier_name) values (15, 'Wolf, Heidenreich and Frami');
insert into PartsSupplier (id, supplier_name) values (16, 'Hagenes, Boehm and Corwin');
insert into PartsSupplier (id, supplier_name) values (17, 'Weimann, Pollich and Heaney');
insert into PartsSupplier (id, supplier_name) values (18, 'Toy, Ledner and Reinger');
insert into PartsSupplier (id, supplier_name) values (19, 'Ruecker, Wyman and Konopelski');
insert into PartsSupplier (id, supplier_name) values (20, 'Wiegand Group');
insert into PartsSupplier (id, supplier_name) values (21, 'Flatley, Bauch and Oberbrunner');
insert into PartsSupplier (id, supplier_name) values (22, 'Kozey-Konopelski');
insert into PartsSupplier (id, supplier_name) values (23, 'Howe LLC');
insert into PartsSupplier (id, supplier_name) values (24, 'Abernathy-Heathcote');
insert into PartsSupplier (id, supplier_name) values (25, 'Sporer LLC');
insert into PartsSupplier (id, supplier_name) values (26, 'Ondricka, Klein and Weimann');
insert into PartsSupplier (id, supplier_name) values (27, 'Blick, Botsford and Kunde');
insert into PartsSupplier (id, supplier_name) values (28, 'Maggio and Sons');
insert into PartsSupplier (id, supplier_name) values (29, 'Morissette Inc');
insert into PartsSupplier (id, supplier_name) values (30, 'Sporer, McKenzie and Aufderhar');
