insert into Parts (id, supplier_id, part_name, unit_price) values (1, 30, 'Solid Oak Board 2m', 46);
insert into Parts (id, supplier_id, part_name, unit_price) values (2, 18, 'Solid Pine Plank 2m', 100);
insert into Parts (id, supplier_id, part_name, unit_price) values (3, 13, 'Plywood Sheet 12mm', 16);
insert into Parts (id, supplier_id, part_name, unit_price) values (4, 22, 'MDF Panel 18mm', 68);
insert into Parts (id, supplier_id, part_name, unit_price) values (5, 24, 'Walnut Veneer Strip', 50);
insert into Parts (id, supplier_id, part_name, unit_price) values (6, 5, 'M6 Steel Bolt', 40);
insert into Parts (id, supplier_id, part_name, unit_price) values (7, 14, 'M8 Steel Bolt', 71);
insert into Parts (id, supplier_id, part_name, unit_price) values (8, 30, 'Wood Screw 30mm', 100);
insert into Parts (id, supplier_id, part_name, unit_price) values (9, 28, 'Wood Screw 50mm', 14);
insert into Parts (id, supplier_id, part_name, unit_price) values (10, 22, 'Wooden Dowel 8mm', 7);
insert into Parts (id, supplier_id, part_name, unit_price) values (11, 30, 'Wooden Dowel 10mm', 9);
insert into Parts (id, supplier_id, part_name, unit_price) values (12, 23, 'Cam Lock Nut', 26);
insert into Parts (id, supplier_id, part_name, unit_price) values (13, 9, 'Connecting Bolt', 67);
insert into Parts (id, supplier_id, part_name, unit_price) values (14, 24, 'Soft-Close Hinge', 68);
insert into Parts (id, supplier_id, part_name, unit_price) values (15, 4, 'Standard Door Hinge', 78);
insert into Parts (id, supplier_id, part_name, unit_price) values (16, 22, 'Magnetic Cabinet Catch', 5);
insert into Parts (id, supplier_id, part_name, unit_price) values (17, 13, 'Ball Bearing Drawer Slide 40cm', 88);
insert into Parts (id, supplier_id, part_name, unit_price) values (18, 16, 'Drawer Rail 50cm', 10);
insert into Parts (id, supplier_id, part_name, unit_price) values (19, 19, 'Metal Corner Bracket', 98);
insert into Parts (id, supplier_id, part_name, unit_price) values (20, 6, 'Shelf Support Peg', 56);
insert into Parts (id, supplier_id, part_name, unit_price) values (21, 2, 'Brushed Steel Handle', 31);
insert into Parts (id, supplier_id, part_name, unit_price) values (22, 28, 'Matte Black Cabinet Knob', 51);
insert into Parts (id, supplier_id, part_name, unit_price) values (23, 12, 'Antique Brass Pull', 96);
insert into Parts (id, supplier_id, part_name, unit_price) values (24, 8, 'Solid Oak Tapered Leg', 38);
insert into Parts (id, supplier_id, part_name, unit_price) values (25, 30, 'Metal Hairpin Leg 45cm', 50);
insert into Parts (id, supplier_id, part_name, unit_price) values (26, 13, 'Plastic Floor Glide', 54);
insert into Parts (id, supplier_id, part_name, unit_price) values (27, 23, 'Caster Wheel M10', 83);
insert into Parts (id, supplier_id, part_name, unit_price) values (28, 18, 'High-Density Seat Foam', 98);
insert into Parts (id, supplier_id, part_name, unit_price) values (29, 11, 'Memory Foam Layer', 50);
insert into Parts (id, supplier_id, part_name, unit_price) values (30, 19, 'Polyester Upholstery Fabric', 75);
insert into Parts (id, supplier_id, part_name, unit_price) values (31, 19, 'Genuine Leather Swatch', 26);
insert into Parts (id, supplier_id, part_name, unit_price) values (32, 7, 'Velvet Fabric Navy', 95);
insert into Parts (id, supplier_id, part_name, unit_price) values (33, 30, 'Zig-Zag Sofa Spring', 11);
insert into Parts (id, supplier_id, part_name, unit_price) values (34, 28, 'Pocket Spring Unit', 65);
insert into Parts (id, supplier_id, part_name, unit_price) values (35, 2, 'Upholstery Staple', 82);
insert into Parts (id, supplier_id, part_name, unit_price) values (36, 21, 'Wood Glue 500ml', 95);
insert into Parts (id, supplier_id, part_name, unit_price) values (37, 22, 'Tempered Glass Top 60cm', 89);
insert into Parts (id, supplier_id, part_name, unit_price) values (38, 24, 'Mirror Panel 100x40', 23);
insert into Parts (id, supplier_id, part_name, unit_price) values (39, 20, 'Aluminum Door Frame', 91);
insert into Parts (id, supplier_id, part_name, unit_price) values (40, 29, 'L-Shaped Section', 64);
insert into Parts (id, supplier_id, part_name, unit_price) values (41, 6, 'Steel Crossbar', 94);
insert into Parts (id, supplier_id, part_name, unit_price) values (42, 19, 'Felt Furniture Pad', 26);
insert into Parts (id, supplier_id, part_name, unit_price) values (43, 11, 'Allen Key 4mm', 57);
insert into Parts (id, supplier_id, part_name, unit_price) values (44, 1, 'Allen Key 5mm', 2);
insert into Parts (id, supplier_id, part_name, unit_price) values (45, 27, 'Adjustable Leveling Foot', 16);
insert into Parts (id, supplier_id, part_name, unit_price) values (46, 11, 'Plastic Screw Cap', 19);
insert into Parts (id, supplier_id, part_name, unit_price) values (47, 5, 'Edge Banding Tape', 84);
insert into Parts (id, supplier_id, part_name, unit_price) values (48, 1, 'Woven Webbing Strap', 54);
insert into Parts (id, supplier_id, part_name, unit_price) values (49, 14, 'Backrest Support Rail', 67);
insert into Parts (id, supplier_id, part_name, unit_price) values (50, 3, 'Armchair Frame Link', 12);
