insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (1, 'Heritage Brass Ottoman', 403.92, 27, 41, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (2, 'Loft Ash Sideboard', 212.74, 11, 19, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (3, 'Scandinavian Leather Sofa', 217.61, 31, 4, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (4, 'Mid-Century Mahogany Wardrobe', 95.47, 100, 10, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (5, 'Urban Rattan Nightstand', 83.1, 31, 7, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (6, 'Scandinavian Metal Sofa', 409.11, 96, 9, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (7, 'Loft Ash Sideboard', 185.74, 28, 11, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (8, 'Loft Steel Sideboard', 365.99, 2, 45, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (9, 'Vintage Pine Dining Table', 384.7, 49, 14, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (10, 'Loft Rattan Bench', 461.47, 43, 32, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (11, 'Rustic Velvet Bed', 195.52, 3, 24, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (12, 'Vintage Walnut Desk', 373.78, 98, 35, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (13, 'Minimalist Walnut Dining Table', 391.25, 4, 22, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (14, 'Contemporary Rattan Desk', 70.6, 47, 48, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (15, 'Coastal Brass Dresser', 302.62, 29, 41, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (16, 'Contemporary Fabric Desk', 311.57, 17, 44, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (17, 'Urban Ash Nightstand', 260.12, 30, 16, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (18, 'Minimalist Walnut Armchair', 185.8, 19, 10, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (19, 'Urban Ash Nightstand', 440.43, 9, 37, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (20, 'Mid-Century Pine Wardrobe', 231.09, 86, 33, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (21, 'Luxury Pine Coffee Table', 110.99, 62, 7, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (22, 'Urban Mahogany Ottoman', 416.02, 61, 10, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (23, 'Luxury Metal Coffee Table', 115.51, 25, 14, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (24, 'Loft Rattan Bench', 389.95, 97, 47, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (25, 'Contemporary Teak Desk', 376.88, 56, 27, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (26, 'Nordic Mahogany Sideboard', 304.07, 56, 13, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (27, 'Vintage Walnut Desk', 245.11, 1, 2, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (28, 'Heritage Marble Ottoman', 278.81, 9, 5, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (29, 'Alpine Ash Bench', 285.53, 6, 5, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (30, 'Rustic Velvet Console Table', 385.09, 76, 22, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (31, 'Coastal Brass Dresser', 392.16, 83, 2, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (32, 'Industrial Metal Coffee Table', 424.27, 48, 47, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (33, 'Modern Pine TV Stand', 397.46, 80, 25, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (34, 'Industrial Walnut Bed', 113.91, 30, 46, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (35, 'Rustic Leather Console Table', 154.6, 12, 12, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (36, 'Scandinavian Leather Sofa', 381.35, 77, 7, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (37, 'Scandinavian Metal Sofa', 346.93, 63, 18, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (38, 'Coastal Velvet Dresser', 260.63, 9, 9, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (39, 'Luxury Metal Coffee Table', 103.45, 31, 18, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (40, 'Modern Oak TV Stand', 68.83, 18, 31, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (41, 'Industrial Leather Bed', 149.56, 44, 37, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (42, 'Urban Steel Nightstand', 316.28, 72, 29, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (43, 'Rustic Velvet Bed', 450.61, 56, 9, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (44, 'Loft Ash Sideboard', 348.48, 94, 37, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (45, 'Modern Velvet TV Stand', 354.15, 77, 17, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (46, 'Alpine Marble TV Stand', 499.06, 54, 23, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (47, 'Luxury Metal Wardrobe', 441.09, 79, 27, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (48, 'Heritage Marble Ottoman', 483.51, 18, 15, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (49, 'Minimalist Walnut Armchair', 161.45, 74, 27, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (50, 'Vintage Teak Dining Table', 471.43, 34, 13, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (51, 'Vintage Walnut Desk', 332.09, 33, 16, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (52, 'Loft Ash Sideboard', 367.07, 52, 39, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (53, 'Heritage Ash Ottoman', 143.41, 74, 7, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (54, 'Loft Ash Sideboard', 76.53, 26, 13, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (55, 'Luxury Walnut Coffee Table', 352.77, 87, 46, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (56, 'Minimalist Pine Armchair', 66.3, 61, 10, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (57, 'Mid-Century Teak Wardrobe', 358.13, 24, 36, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (58, 'Alpine Pine Bench', 244.68, 76, 17, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (59, 'Nordic Mahogany Bookshelf', 174.87, 52, 13, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (60, 'Minimalist Pine Armchair', 300.97, 63, 17, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (61, 'Minimalist Glass Armchair', 133.1, 51, 26, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (62, 'Luxury Walnut Coffee Table', 67.96, 10, 27, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (63, 'Heritage Brass Ottoman', 351.01, 15, 46, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (64, 'Vintage Walnut Dining Table', 303.49, 0, 8, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (65, 'Vintage Teak Dining Table', 206.88, 78, 4, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (66, 'Mid-Century Fabric Wardrobe', 428.76, 63, 30, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (67, 'Rustic Velvet Console Table', 465.27, 44, 43, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (68, 'Contemporary Mahogany Desk', 80.09, 27, 6, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (69, 'Nordic Steel Bookshelf', 312.39, 28, 13, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (70, 'Minimalist Walnut Dining Table', 95.7, 54, 17, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (71, 'Loft Steel Bench', 479.92, 41, 17, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (72, 'Rustic Oak Bed', 138.25, 34, 4, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (73, 'Contemporary Mahogany Nightstand', 401.91, 49, 33, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (74, 'Urban Steel Nightstand', 339.93, 50, 30, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (75, 'Mid-Century Fabric Wardrobe', 163.22, 34, 18, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (76, 'Nordic Mahogany Bookshelf', 298.59, 73, 38, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (77, 'Heritage Marble Ottoman', 62.57, 74, 12, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (78, 'Luxury Metal Coffee Table', 155.96, 1, 48, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (79, 'Rustic Oak Bed', 266.61, 7, 39, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (80, 'Vintage Teak Dining Table', 254.9, 74, 44, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (81, 'Contemporary Teak Desk', 242.71, 64, 43, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (82, 'Coastal Marble Console Table', 392.03, 34, 35, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (83, 'Heritage Marble Ottoman', 366.16, 4, 26, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (84, 'Alpine Marble Bench', 112.54, 15, 27, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (85, 'Alpine Marble Bench', 228.05, 10, 39, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (86, 'Luxury Fabric Wardrobe', 138.06, 88, 36, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (87, 'Coastal Marble Console Table', 80.57, 10, 6, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (88, 'Mid-Century Pine Wardrobe', 245.68, 48, 36, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (89, 'Loft Steel Sideboard', 320.2, 8, 35, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (90, 'Minimalist Metal Dining Table', 367.3, 32, 48, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (91, 'Mid-Century Teak Wardrobe', 148.01, 23, 30, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (92, 'Urban Steel Nightstand', 452.51, 84, 20, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (93, 'Coastal Marble Console Table', 313.31, 12, 13, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (94, 'Industrial Walnut Bed', 247.68, 2, 34, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (95, 'Alpine Pine Bench', 384.66, 47, 48, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (96, 'Contemporary Mahogany Desk', 209.09, 53, 25, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (97, 'Minimalist Pine Armchair', 324.9, 76, 2, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (98, 'Alpine Marble Bench', 176.71, 85, 42, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (99, 'Urban Mahogany Ottoman', 370.25, 0, 38, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (100, 'Mid-Century Mahogany Wardrobe', 447.49, 25, 44, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (101, 'Mid-Century Teak Wardrobe', 279.12, 46, 19, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (102, 'Rustic Velvet Console Table', 113.57, 27, 39, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (103, 'Rustic Pine Console Table', 343.03, 47, 10, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (104, 'Nordic Steel Bookshelf', 219.72, 32, 5, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (105, 'Mid-Century Teak Wardrobe', 303.33, 27, 15, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (106, 'Mid-Century Teak Wardrobe', 484.46, 46, 28, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (107, 'Nordic Steel Bookshelf', 433.14, 63, 38, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (108, 'Alpine Marble TV Stand', 51.01, 42, 29, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (109, 'Nordic Teak Bookshelf', 383.52, 88, 46, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (110, 'Minimalist Glass Armchair', 242.8, 63, 15, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (111, 'Luxury Metal Coffee Table', 197.85, 48, 33, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (112, 'Modern Pine TV Stand', 455.24, 41, 10, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (113, 'Rustic Pine Console Table', 136.44, 33, 8, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (114, 'Nordic Teak Sideboard', 285.48, 59, 21, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (115, 'Industrial Glass Bed', 395.43, 13, 4, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (116, 'Modern Oak Sofa', 152.65, 98, 15, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (117, 'Minimalist Metal Armchair', 307.63, 45, 29, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (118, 'Urban Ash Nightstand', 365.59, 49, 41, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (119, 'Contemporary Fabric Desk', 422.36, 50, 32, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (120, 'Urban Mahogany Nightstand', 242.49, 9, 46, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (121, 'Modern Marble TV Stand', 348.61, 34, 26, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (122, 'Mid-Century Fabric Wardrobe', 296.56, 0, 12, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (123, 'Luxury Pine Coffee Table', 154.41, 45, 5, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (124, 'Urban Rattan Ottoman', 459.76, 12, 4, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (125, 'Heritage Steel Ottoman', 55.74, 22, 45, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (126, 'Urban Mahogany Nightstand', 265.61, 52, 35, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (127, 'Alpine Marble Bench', 427.29, 22, 45, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (128, 'Scandinavian Oak Armchair', 371.33, 54, 35, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (129, 'Heritage Ash Ottoman', 129.55, 47, 45, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (130, 'Coastal Brass Dresser', 417.01, 63, 35, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (131, 'Minimalist Pine Armchair', 130.41, 76, 33, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (132, 'Heritage Brass Ottoman', 320.54, 54, 48, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (133, 'Contemporary Fabric Nightstand', 218.94, 25, 11, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (134, 'Coastal Pine Dresser', 206.0, 42, 7, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (135, 'Nordic Teak Sideboard', 342.44, 72, 6, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (136, 'Industrial Metal Coffee Table', 217.05, 8, 13, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (137, 'Modern Marble Sofa', 103.15, 83, 28, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (138, 'Luxury Pine Coffee Table', 113.68, 50, 16, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (139, 'Scandinavian Glass Sofa', 62.11, 98, 37, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (140, 'Nordic Rattan Sideboard', 79.38, 79, 46, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (141, 'Contemporary Mahogany Nightstand', 253.66, 44, 17, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (142, 'Luxury Pine Coffee Table', 164.02, 58, 44, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (143, 'Vintage Fabric Dining Table', 444.97, 74, 10, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (144, 'Urban Steel Nightstand', 415.17, 85, 20, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (145, 'Minimalist Walnut Armchair', 111.57, 25, 9, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (146, 'Mid-Century Fabric Wardrobe', 123.4, 40, 8, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (147, 'Urban Mahogany Nightstand', 337.36, 58, 17, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (148, 'Mid-Century Fabric Bookshelf', 229.92, 38, 38, 7);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (149, 'Rustic Oak Console Table', 467.9, 86, 5, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (150, 'Vintage Glass Desk', 116.51, 43, 15, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (151, 'Mid-Century Teak Bookshelf', 496.79, 92, 37, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (152, 'Scandinavian Metal Sofa', 374.54, 93, 20, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (153, 'Mid-Century Pine Wardrobe', 102.06, 68, 31, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (154, 'Industrial Metal Bed', 305.95, 77, 48, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (155, 'Luxury Walnut Coffee Table', 459.75, 92, 8, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (156, 'Vintage Pine Desk', 130.49, 84, 48, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (157, 'Minimalist Glass Armchair', 409.28, 68, 9, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (158, 'Nordic Rattan Bookshelf', 260.26, 79, 8, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (159, 'Alpine Brass Bench', 201.43, 56, 39, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (160, 'Industrial Leather Bed', 225.45, 33, 16, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (161, 'Coastal Pine Dresser', 123.75, 99, 41, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (162, 'Alpine Marble Bench', 185.27, 86, 31, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (163, 'Luxury Pine Coffee Table', 452.86, 50, 7, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (164, 'Urban Rattan Nightstand', 150.14, 46, 23, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (165, 'Mid-Century Fabric Wardrobe', 466.56, 1, 4, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (166, 'Coastal Pine Dresser', 283.21, 58, 17, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (167, 'Modern Oak TV Stand', 432.46, 28, 20, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (168, 'Minimalist Pine Armchair', 427.72, 31, 5, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (169, 'Mid-Century Fabric Bookshelf', 482.09, 68, 33, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (170, 'Vintage Teak Dining Table', 306.62, 37, 28, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (171, 'Nordic Mahogany Sideboard', 287.37, 48, 29, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (172, 'Urban Steel Ottoman', 198.79, 27, 45, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (173, 'Scandinavian Metal Sofa', 368.22, 14, 11, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (174, 'Urban Steel Nightstand', 271.09, 14, 48, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (175, 'Alpine Marble Bench', 445.76, 21, 24, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (176, 'Minimalist Pine Armchair', 232.09, 90, 9, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (177, 'Coastal Marble Dresser', 147.64, 45, 12, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (178, 'Heritage Brass Ottoman', 341.28, 61, 32, 8);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (179, 'Loft Rattan Sideboard', 306.65, 93, 16, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (180, 'Industrial Leather Bed', 383.73, 0, 21, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (181, 'Vintage Fabric Dining Table', 495.69, 68, 20, 5);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (182, 'Rustic Velvet Bed', 454.02, 57, 14, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (183, 'Vintage Teak Dining Table', 171.2, 2, 25, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (184, 'Modern Oak TV Stand', 259.22, 67, 20, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (185, 'Alpine Pine Bench', 330.58, 26, 25, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (186, 'Heritage Marble Ottoman', 315.23, 74, 25, 3);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (187, 'Loft Steel Bench', 393.43, 12, 26, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (188, 'Alpine Pine Bench', 296.54, 11, 17, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (189, 'Rustic Leather Console Table', 251.96, 22, 20, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (190, 'Coastal Marble Dresser', 259.5, 90, 31, 9);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (191, 'Mid-Century Pine Wardrobe', 89.99, 20, 35, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (192, 'Modern Marble Sofa', 246.73, 76, 10, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (193, 'Alpine Marble Bench', 427.03, 24, 2, 1);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (194, 'Industrial Leather Coffee Table', 497.04, 38, 48, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (195, 'Mid-Century Teak Wardrobe', 388.69, 91, 25, 2);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (196, 'Heritage Marble Ottoman', 460.52, 51, 47, 10);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (197, 'Alpine Pine Bench', 257.83, 21, 31, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (198, 'Scandinavian Oak Armchair', 432.24, 18, 16, 4);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (199, 'Mid-Century Teak Bookshelf', 335.51, 23, 27, 6);
insert into Products (id, name, labor_price, current_stock, production_time_hours, category_id) values (200, 'Minimalist Walnut Armchair', 298.48, 70, 2, 8);
