insert into Shippers (id, shipper_name) values (1, 'FedEx Freight');
insert into Shippers (id, shipper_name) values (2, 'UPS Ground');
insert into Shippers (id, shipper_name) values (3, 'DHL Home Delivery');
insert into Shippers (id, shipper_name) values (4, 'XPO Logistics');
insert into Shippers (id, shipper_name) values (5, 'J.B. Hunt Transport');
insert into Shippers (id, shipper_name) values (6, 'Ryder System');
insert into Shippers (id, shipper_name) values (7, 'Schneider National');
insert into Shippers (id, shipper_name) values (8, 'Old Dominion Freight Line');
insert into Shippers (id, shipper_name) values (9, 'Estes Express Lines');
insert into Shippers (id, shipper_name) values (10, 'ArcBest (ABF Freight)');
insert into Shippers (id, shipper_name) values (11, 'TForce Freight');
insert into Shippers (id, shipper_name) values (12, 'Saia LTL Freight');
insert into Shippers (id, shipper_name) values (13, 'R+L Carriers');
insert into Shippers (id, shipper_name) values (14, 'Averitt Express');
insert into Shippers (id, shipper_name) values (15, 'Southeastern Freight Lines');
insert into Shippers (id, shipper_name) values (16, 'Pitt Ohio');
insert into Shippers (id, shipper_name) values (17, 'Ward Trucking');
insert into Shippers (id, shipper_name) values (18, 'Oak Harbor Freight Lines');
insert into Shippers (id, shipper_name) values (19, 'Dayton Freight');
insert into Shippers (id, shipper_name) values (20, 'AAA Cooper Transportation');
insert into Shippers (id, shipper_name) values (21, 'Central Transport');
insert into Shippers (id, shipper_name) values (22, 'Roadrunner Freight');
insert into Shippers (id, shipper_name) values (23, 'Forward Air');
insert into Shippers (id, shipper_name) values (24, 'Landstar System');
insert into Shippers (id, shipper_name) values (25, 'Knight-Swift Transportation');
insert into Shippers (id, shipper_name) values (26, 'Werner Enterprises');
insert into Shippers (id, shipper_name) values (27, 'C.H. Robinson');
insert into Shippers (id, shipper_name) values (28, 'Coyote Logistics');
insert into Shippers (id, shipper_name) values (29, 'Echo Global Logistics');
insert into Shippers (id, shipper_name) values (30, 'Deliveright Logistics');
